### ISSUE TITLE
Error in startsession

### ISSUE THREAD

**Issue by Hamdan-Maharoof** [Git-Kar33/Project-group4_infs3203#15]
![image](https://github.com/Git-Kar33/Project-group4_infs3203/assets/158258733/3caecdf6-ca49-4fc5-b9b8-61baa68bc7ae)

There is an error to this code as the session_start function prints incorrect data, can you write to fix the code in the staging branch

**Comment by Hamdan-Maharoof** [comment]
Ok, i will find good logical ways to fix it

**Comment by Hamdan-Maharoof** [comment]
Fixed it...The solution was simple as we did not need extra form of return, so this logic is better.. make sure to pull it

**Comment by MohamedElsabonabi** [comment]
alright great !! I will do the workflow as follows

**Comment by Hamdan-Maharoof** [comment]
for pushing and merging
