### ISSUE TITLE
Test Fix

### ISSUE THREAD

**Issue by Git-Kar33** [Git-Kar33/Project-group4_infs3203#4]
![image](https://github.com/Git-Kar33/Project-group4_infs3203/assets/141827107/2fc518b1-2f7e-4d8b-8b66-5137b4c84fb5)

Team, we are doing good job in testing file, but still we are running with bit of issue with test and lets add for better and efficient testing

**Comment by Hamdan-Maharoof** [comment]
yes I will be adding more ... and fix the issue ..

**Comment by mazinthaj** [comment]
Alright, I will also try to fix the issue and more test
