### ISSUE TITLE
Work Flow Fix

### ISSUE THREAD

**Issue by mazinthaj** [Git-Kar33/Project-group4_infs3203#5]
![image](https://github.com/Git-Kar33/Project-group4_infs3203/assets/158258240/89f0fea1-8075-4ed2-9046-2bbb1047d8ec)

Guys, we are still we are facing issue with workflow

**Comment by Git-Kar33** [comment]
Noted

**Comment by Git-Kar33** [comment]
![image](https://github.com/Git-Kar33/Project-group4_infs3203/assets/141827107/61059a8a-6a05-4a7d-b267-55fc93265e98)

The main issue it keeps on running non stop
