### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by Hamdan-Maharoof** [Git-Kar33/Project-group4_infs3203#6]
![image](https://github.com/Git-Kar33/Project-group4_infs3203/assets/158258733/f7acc604-317a-4aab-ae67-e2ee581caea0)

Team, issue with the deployment while testing. Permission error

**Comment by mazinthaj** [comment]
ok lets work on it

**Comment by Git-Kar33** [comment]
Probably has to do with settings .. or maybe yml file .. we will double check it

**Comment by mazinthaj** [comment]
![image](https://github.com/Git-Kar33/Project-group4_infs3203/assets/158258240/67cd616d-222d-4662-aab6-2369bf69683f)

yea worked on it .. as a sample it was with permissions right. For now lets consider it as done and move on to new steps

**Comment by Git-Kar33** [comment]
Wow Good job !! lets proceed on to next step as we need more workflows .. lets see any future issues we will fix as we discuss here

**Comment by Hamdan-Maharoof** [comment]
Good job team!! yes we may run into issue but lets discuss it in here...
